max_frames: 100
sim_size:
  width: 1440
  height: 1920
on_frame:
  show_preview:
    max_width: 1000
    max_height: 1000
    frames_per_render: 10
#  export_raster:
#    scale: 2
#    filename: "/Users/alex/projects/spacefiller/output/frame-%04d.tif"
on_complete:
#  export_raster:
#    scale: 2
#    filename: "/Users/alex/projects/spacefiller/output.png"
  export_svg:
    filename: "/Users/alex/projects/spacefiller/output.svg"
#  - save_svg:
#      size:
#        max_width: 1000
#        max_height: 1000
render_frames: false
render_preview: true
max_particles: 100000
plants:
  min: 10
  max: 40
  types:
    - branch_color: 0xffffffff
      flower_color: 0xffffffff
      connection_length: 5
      branching_factor: 2
      branching_falloff: 0.1
      seed_branching_factor: 3
      branching_factor_deviation: 0
      max_depth: 2
      max_depth_deviation: 3
      branch_chance: 0.5
      flower_size: 3
      branch_thickness: 1
    - branch_color: 0xffffffff
      flower_color: 0xffffffff
      connection_length: 2
      branching_factor: 2
      branching_falloff: 0.1
      seed_branching_factor: 10
      branching_factor_deviation: 2
      max_depth: 2
      max_depth_deviation: 3
      branch_chance: 0
      flower_size: 3
      branch_thickness: 1
    - branch_color: 0xffffffff
      flower_color: 0xffffffff
      connection_length: 2
      branching_factor: 2
      branching_falloff: 0.1
      seed_branching_factor: 0
      branching_factor_deviation: 2
      max_depth: 20
      max_depth_deviation: 3
      branch_chance: 0
      flower_size: 5
      branch_thickness: 1
hives:
  min: 500
  max: 600
  line_thickness: 1
  #  min: 0
  #  max: 0
  global_repel_threshold: 10
  bees_per_hive: 3
  initial_bees_per_hive: 0
  hive_size: 10
  hive_size_deviation: 25
  hive_flattening_force: 0.5
  hive_inner_repel_force: 0.02
  spikes: false
  colors:
    - bee_color: 0xffffffff
      hive_color: 0xffffffff
    - bee_color: 0xffffffff
      hive_color: 0x00000000
  flocking:
    separation_weight: 2
    alignment_weight: 2
    cohesion_weight: 1
    alignment_threshold: 40
    cohesion_threshold: 40
    desired_threshold: 10
    max_speed: 0.5f
    max_force: 0.01f
dust:
  count: 5000
  repel_threshold: 6
  repel_hive_threshold: 1
planet_system:
  repel_threshold: 50
  attraction_threshold: 400
  noise_amplitude: 50
  noise_scale: 0.01
  sdf_smooth: 0.1
  planets:
    - min_radius: 150
      max_radius: 250
      tags: [DUST, HIVE_LIGHT, HIVE_DARK]
    - min_radius: 100
      max_radius: 200
      tags: [DUST, HIVE_LIGHT, HIVE_DARK]
    - min_radius: 150
      max_radius: 250
      tags: [DUST, HIVE_LIGHT]
    - min_radius: 100
      max_radius: 200
      tags: [DUST, HIVE_DARK]
    - min_radius: 50
      max_radius: 100
      tags: [DUST, HIVE_DARK]
    - min_radius: 50
      max_radius: 100
      tags: [HIVE_LIGHT]
    - min_radius: 70
      max_radius: 100
      tags: [PLANT]
    - min_radius: 50
      max_radius: 100
      tags: [PLANT]
    - min_radius: 150
      max_radius: 250
      tags: [DUST, HIVE_LIGHT, HIVE_DARK]
    - min_radius: 100
      max_radius: 200
      tags: [DUST, HIVE_LIGHT, HIVE_DARK]
    - min_radius: 150
      max_radius: 250
      tags: [DUST, HIVE_LIGHT]
    - min_radius: 100
      max_radius: 200
      tags: [DUST, HIVE_DARK]
    - min_radius: 50
      max_radius: 100
      tags: [DUST, HIVE_DARK]
    - min_radius: 50
      max_radius: 100
      tags: [HIVE_LIGHT]
    - min_radius: 70
      max_radius: 100
      tags: [PLANT]
    - min_radius: 50
      max_radius: 100
      tags: [PLANT]
#    - min_radius: 200
#      max_radius: 400
#      tags: [DUST, HIVE_DARK, HIVE_LIGHT]
#    - min_radius: 100
#      max_radius: 300
#      tags: [DUST, HIVE_DARK, HIVE_LIGHT]
#    - min_radius: 100
#      max_radius: 200
#      tags: [DUST, HIVE, HIVE_DARK, HIVE_LIGHT]

#    - min_radius: 50
#      max_radius: 100
#      tags: [HIVE_LIGHT]
#    - min_radius: 50
#      max_radius: 100
#      tags: [HIVE_LIGHT]

#    - min_radius: 30
#      max_radius: 50
#      tags: [HIVE_LIGHT]
#    - min_radius: 30
#      max_radius: 50
#      tags: [HIVE]
#    - min_radius: 50
#      max_radius: 100
#      tags: [PLANT]

