max_frames: 2000
render_frames: false
render_preview: true
max_particles: 100000
background_on: true
background_color: 0xff000000
sim_size:
  width: 540
  height: 720
render_size:
  width: 540
  height: 720
hives:
  min: 500
  max: 500
  line_thickness: 1
#  min: 0
#  max: 0
  global_repel_threshold: 5
  bees_per_hive: 0
  initial_bees_per_hive: 0
  hive_size: 0
  hive_size_deviation: 25
  hive_flattening_force: 0.5
  hive_inner_repel_force: 0.02
  spikes: false
  colors:
    - bee_color: 0xffffff99
      hive_color: 0xffffffff
    - bee_color: 0xffffffcc
      hive_color: 0xffffffff
dust:
  count: 10000
  repel_threshold: 10
planets:
  min: 4
  max: 4
  min_radius: 100
  max_radius: 200
  repel_threshold: 40
  attraction_threshold: 200
  noise_amplitude: 0
  noise_scale: 0.01
  sdf_smooth: 0.1