max_frames: 2000
max_particles: 20000
sim_size:
  width: 192
  height: 250
render_size:
  width: 768
  height: 1000
plants:
  min: 4
  max: 4
  types:
    - branch_color: 0xffffffff
      flower_color: 0xffd3d3d3
      branching_factor: 1
      branch_chance: 0.1f
      flower_size: 4
      max_depth: 40
    - max_depth: 10
      branching_factor: 4
      seed_branching_factor: 4
      branching_falloff: -1
      branch_chance: 0.5
      branch_color: 0xffa7c45a
      flower_color: 0xffa7c45a
    - branch_chance: 0.1f
      branch_color: 0xff539852
      flower_color: 0xff87c38e
      max_depth: 20
      branching_factor: 2
    - branch_color: 0xffa7c45a
      flower_color: 0xffffffff
      branch_chance: 0.4f
    - flower_colors: [0xffd8e9f6, 0xff627dab]
      branch_colors: [0xff87c38e, 0xffc6ffc5]
      flower_size: 3
      flower_deviation: 4
#    - max_depth: 40
#      max_depth_deviation: 10
#      mass: 0.5f
#      branch_color: 0xff47759c
#      flower_color: 0xff84f2bf
#      seed_branching_factor: 5
#      branch_chance: 0
#      flower_size: 10
#    - flower_colors: [0xff84b7ad, 0xff8f305e]
#      max_depth: 3
#      max_depth_deviation: 2
#      branch_color: 0xff84b7ad
#      seed_branching_factor: 20
#      branching_factor_deviation: 10
#      branch_chance: 0
#      flower_size: 6

hives:
  min: 2
  max: 2
  bees_per_hive: 20
  initial_bees_per_hive: 20
  hive_size: 10
  hive_size_deviation: 10
  colors:
    - bee_color: 0xffe2e1a2
      hive_color: 0xffe2e1a2
#    - bee_color: 0xffffc98f
#      hive_color: 0xffffc98f
dust:
  count: 200
