max_frames: 500
max_particles: 1000
sim_size:
  width: 200
  height: 200
render_size:
  width: 1000
  height: 1000
plants:
  min: 3
  max: 4
hives:
  min: 1
  max: 2
  bees_per_hive: 50
dust:
  count: 300
circle_constraints:
  - radius: 70
    tag: PLANT
  - radius: 70
    tag: HIVE
  - radius: 95
    tag: BEE
  - radius: 95
    tag: DUST
