max_frames: 300
max_particles: 1000
sim_size:
  width: 200
  height: 200
render_size:
  width: 1000
  height: 1000
plants:
  min: 5
  max: 5
hives:
  min: 4
  max: 5
  bees_per_hive: 10
dust:
  count: 300
circle_constraint:
  radius: 80