max_frames: 2000
render_frames: false
render_preview: true
max_particles: 20000
background_on: true
background_color: 0xff000000
sim_size:
  width: 540 # 540
  height: 720 # 720
render_size:
  width: 540
  height: 720
plants:
  min: 20
  max: 20
  types:
    - branch_chance: 0.1f
      branch_color: 0xff77BF00
      flower_color: 0xff52FF00
      max_depth: 20
      branching_factor: 2
    - branch_color: 0xff43BF00
      branch_chance: 0.4f
    - flower_colors: [0xffF5FF37, 0xff37FFC9, 0xffB75CFF]
      branch_colors: [0xff2BA637, 0xff23872D, 0xff318723]
      flower_size: 3
      flower_deviation: 4
    - max_depth: 10
      branching_factor: 4
      seed_branching_factor: 4
      branching_falloff: -1
      branch_chance: 0.5
    - max_depth: 40
      max_depth_deviation: 10
      mass: 0.5f
      branch_color: 0xff0052CC
      flower_color: 0xff24C4FF
      seed_branching_factor: 5
      branch_chance: 0
      flower_size: 10
    - flower_colors: [0xff5FC786, 0xffC72E9C]
      max_depth: 3
      max_depth_deviation: 2
      branch_color: 0xff5FC786
      seed_branching_factor: 20
      branching_factor_deviation: 10
      branch_chance: 0
      flower_size: 6
    - branch_color: 0xffffffff
      branching_factor: 1
      branch_chance: 0.1f
      flower_size: 4
      max_depth: 40
hives:
  min: 100
  max: 100
  global_repel_threshold: 20
  bees_per_hive: 0
  initial_bees_per_hive: 5
  hive_size: 0
  hive_size_deviation: 50
  hive_flattening_force: 0.5
  hive_inner_repel_force: 0.02
  spikes: false
  colors:
    - bee_color: 0xffffff99
      hive_color: 0xffffff99
    - bee_color: 0xffffffcc
      hive_color: 0xffffffcc
dust:
  count: 3500
circle_constraints:
  - radius: 300
    deviation: 0
    tag: PLANT
    force: -0.1
  - radius: 300
    deviation: 0
    tag: SEED
    force: -0.1
  - radius: 300
    deviation: 0
    tag: HIVE
  - radius: 290
    deviation: 0
    tag: BEE
    force: -0.1
  - radius: 300
    deviation: 0
    tag: DUST
#    force: -0.1
